CREATE DATABASE IF NOT EXISTS contac_db;
USE contac_db

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRYMARY KEY,
    name VARCHAR (100) NOT NULL,
    email VARCHAR (100)NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

